n = int(input('Digite um número para ver sua tabuada: '))

print('-' * 12)
print('{:2} x {} = {}' .format(1, n, 1*n))
print('{:2} x {} = {}' .format(2, n, 2*n))
print('{:2} x {} = {}' .format(3, n, 3*n))
print('{:2} x {} = {}' .format(4, n, 4*n))
print('{:2} x {} = {}' .format(5, n, 5*n))
print('{:2} x {} = {}' .format(6, n, 6*n))
print('{:2} x {} = {}' .format(7, n, 7*n))
print('{:2} x {} = {}' .format(8, n, 8*n))
print('{:2} x {} = {}' .format(9, n, 9*n))
print('{:2} x {} = {}' .format(10, n, 10*n))
print('-' * 12)
