texto = input('Digite algo: ')
print('O tipo primitivo desse valor é {}', type(texto))
print('Só tem espaços? {}'.format(texto.isspace()))
print('É um número? {}'.format(texto.isnumeric()))
print('É alfabético? {}'.format(texto.isalpha()))
print('É alfanumérico? {}'.format(texto.isalnum()))
print('Está em maiúscula? {}'.format(texto.isupper()))
print('Está em minúscula? {}'.format(texto.islower()))
print('Está capitalizada? {}'.format(texto.istitle()))
